# Generated by Django 5.1.4 on 2025-01-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='A fun interdisciplinary project!', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_nr', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('plant', models.IntegerField(blank=True, null=True)),
                ('investigator', models.IntegerField(blank=True, null=True)),
                ('coordinator', models.IntegerField(blank=True, null=True)),
                ('shaper', models.IntegerField(blank=True, null=True)),
                ('monitor', models.IntegerField(blank=True, null=True)),
                ('teamworker', models.IntegerField(blank=True, null=True)),
                ('implementer', models.IntegerField(blank=True, null=True)),
                ('finisher', models.IntegerField(blank=True, null=True)),
                ('specialist', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_code', models.CharField(max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.student')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.teacher'),
        ),
    ]
